version: '3.9'

services:
  manage-credits-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:778;http://+:922
      - ASPNETCORE_HTTPS_PORTS=14533
      - ASPNETCORE_HTTP_PORTS=12882
    ports:
      - "14533:778"
      - "12882:922"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
